name: budgplan
description: Budget Tracker By Khalid Ibrahim.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.8+4
  charts_flutter: ^0.12.0
  pie_chart: ^5.3.2
  cloud_firestore: ^4.8.1
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/