// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRMrMobsXOUGUxNWKY1-dOuRQjjg_mWbs',
    appId: '1:301075130897:web:091739b2d629fe874c1fb0',
    messagingSenderId: '301075130897',
    projectId: 'budgtracker',
    authDomain: 'budgtracker.firebaseapp.com',
    storageBucket: 'budgtracker.appspot.com',
    measurementId: 'G-ZYD64NEM20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFCJqfmZ1P1D16GIp2-2L2ALeQVEUOpI',
    appId: '1:301075130897:android:1fc0882d073c8fcb4c1fb0',
    messagingSenderId: '301075130897',
    projectId: 'budgtracker',
    storageBucket: 'budgtracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9Hb2UhfFeRjhCslAZ_NHmKvn2-y89Ag',
    appId: '1:301075130897:ios:31024a5028c771bd4c1fb0',
    messagingSenderId: '301075130897',
    projectId: 'budgtracker',
    storageBucket: 'budgtracker.appspot.com',
    iosClientId: '301075130897-qj9hp8g02t0b8sv2ctpgc1gl2o92o2be.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm9Hb2UhfFeRjhCslAZ_NHmKvn2-y89Ag',
    appId: '1:301075130897:ios:31024a5028c771bd4c1fb0',
    messagingSenderId: '301075130897',
    projectId: 'budgtracker',
    storageBucket: 'budgtracker.appspot.com',
    iosClientId: '301075130897-qj9hp8g02t0b8sv2ctpgc1gl2o92o2be.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgplan',
  );
}
